// ===== USER PROFILE MODULE =====

// Load user data from localStorage or use defaults
const DEFAULT_USER_DATA = {
    name: 'SQL Learner',
    handle: 'sql_master_2024',
    bio: 'Mastering the art of data querying. Data Enthusiast | Future Data Scientist.',
    location: 'Global',
    link: 'https://github.com/sql-mastery',
    joined: 'Joined March 2024',
};

let USER_DATA = JSON.parse(localStorage.getItem('sql_user_profile')) || DEFAULT_USER_DATA;

function saveUserData() {
    localStorage.setItem('sql_user_profile', JSON.stringify(USER_DATA));
}

const PINNED_PROJECTS = [
    {
        name: 'ecommerce-analytics',
        desc: 'Complex analysis of sales data, customer behavior, and inventory management using recursive CTEs.',
        lang: 'SQL',
        stars: 8
    },
    {
        name: 'social-graph-query',
        desc: 'Identifying influence patterns and community clusters in a large-scale social network dataset.',
        lang: 'SQL',
        stars: 5
    }
];

function initProfileSection() {
    const container = document.getElementById('section-profile');
    if (!container) return;

    container.innerHTML = `
        <div class="profile-container">
            <!-- Sidebar -->
            <aside class="profile-sidebar">
                <div class="profile-avatar">
                   <i data-lucide="user"></i>
                </div>
                <div class="user-info">
                    <h1 class="user-name">${USER_DATA.name}</h1>
                    <p class="user-handle">${USER_DATA.handle}</p>
                </div>
                <p class="user-bio">${USER_DATA.bio}</p>
                <div id="profile-actions">
                    <button class="btn btn--outline btn--block btn--sm" style="margin: 8px 0;" onclick="showEditProfile()">Edit profile</button>
                </div>
                
                <div class="user-meta" id="profile-meta-display">
                    <div class="user-meta-item">
                        <i data-lucide="map-pin" style="width: 16px;"></i>
                        <span>${USER_DATA.location}</span>
                    </div>
                    <div class="user-meta-item">
                        <i data-lucide="link" style="width: 16px;"></i>
                        <a href="${USER_DATA.link}" target="_blank" style="color: var(--text);">${USER_DATA.link.replace('https://', '') || 'No website'}</a>
                    </div>
                    <div class="user-meta-item">
                        <i data-lucide="calendar" style="width: 16px;"></i>
                        <span>${USER_DATA.joined}</span>
                    </div>
                </div>
            </aside>

            <!-- Main Content -->
            <main class="profile-main">
                <!-- Streak Graph -->
                <div class="streak-card">
                    <div class="streak-title">385 contributions in the last year</div>
                    <div class="streak-graph" id="contribution-graph">
                        <!-- Days generated by JS -->
                    </div>
                </div>

                <!-- Pinned Projects -->
                <div class="pinned-section">
                    <div class="pinned-header">
                        <h3 class="pinned-title">Pinned</h3>
                        <span style="font-size: 0.75rem; color: var(--text-muted); cursor: pointer;">Customize your pins</span>
                    </div>
                    <div class="pinned-grid">
                        ${PINNED_PROJECTS.map(renderPinnedCard).join('')}
                    </div>
                </div>
            </main>
        </div>
    `;

    generateContributionGraph();
    
    if (window.lucide) {
        lucide.createIcons();
    }
}

function renderPinnedCard(project) {
    return `
        <div class="pinned-card">
            <div class="pinned-card-name">
                <i data-lucide="book" style="width: 14px; color: var(--text-muted);"></i>
                ${project.name}
            </div>
            <p class="pinned-card-desc">${project.desc}</p>
            <div class="pinned-card-meta">
                <span><span class="lang-dot"></span> ${project.lang}</span>
                <span><i data-lucide="star" style="width: 12px; vertical-align: middle;"></i> ${project.stars}</span>
            </div>
        </div>
    `;
}

function generateContributionGraph() {
    const graph = document.getElementById('contribution-graph');
    if (!graph) return;

    // Generate 371 squares (53 weeks * 7 days)
    let html = '';
    for (let i = 0; i < 371; i++) {
        // Randomly assign levels for visual effect
        const random = Math.random();
        let level = '';
        if (random > 0.95) level = 'level-4';
        else if (random > 0.85) level = 'level-3';
        else if (random > 0.7) level = 'level-2';
        else if (random > 0.4) level = 'level-1';
        
        html += `<div class="streak-day ${level}" title="Contribution on day ${i}"></div>`;
    }
    graph.innerHTML = html;
}

// GitHub Connection
function handleGitHubConnect() {
    const btn = document.getElementById('btn-github-connect');
    if (!btn) return;

    btn.innerHTML = `<i data-lucide="loader" class="spin" style="width: 14px;"></i> Connecting...`;
    lucide.createIcons();

    setTimeout(() => {
        btn.innerHTML = `<i data-lucide="github" style="width: 16px;"></i> Connected`;
        btn.classList.add('btn--success');
        lucide.createIcons();
        
        // Update user data with "Real" GitHub info
        USER_DATA.name = 'Kaustav Majumder'; // Sample name
        USER_DATA.handle = 'kaustav-m';
        USER_DATA.joined = 'Joined 2021';
        
        // If we are on profile section, re-render
        if (document.getElementById('section-profile').style.display !== 'none') {
            initProfileSection();
        }
        
        // Show success alert
        alert('Successfully linked with your GitHub account!');
    }, 1200);
}

function showEditProfile() {
    const sidebar = document.querySelector('.profile-sidebar');
    const actions = document.getElementById('profile-actions');
    const meta = document.getElementById('profile-meta-display');
    const bio = document.querySelector('.user-bio');
    const nameH1 = document.querySelector('.user-name');

    // Create edit form
    bio.style.display = 'none';
    meta.style.display = 'none';
    
    nameH1.innerHTML = `<input type="text" id="edit-name" value="${USER_DATA.name}" class="form-control" style="font-size: 1.5rem; width: 100%;">`;
    
    actions.innerHTML = `
        <div class="edit-fields" style="margin-bottom: 12px;">
            <label style="font-size: 12px; color: var(--text-muted);">Bio</label>
            <textarea id="edit-bio" class="form-control" style="width: 100%; height: 80px; margin-bottom: 8px;">${USER_DATA.bio}</textarea>
            
            <label style="font-size: 12px; color: var(--text-muted);">Location</label>
            <input type="text" id="edit-location" value="${USER_DATA.location}" class="form-control" style="width: 100%; margin-bottom: 8px;">
            
            <label style="font-size: 12px; color: var(--text-muted);">Website</label>
            <input type="text" id="edit-link" value="${USER_DATA.link}" class="form-control" style="width: 100%; margin-bottom: 12px;">
            
            <div style="display: flex; gap: 8px;">
                <button class="btn btn--success btn--sm btn--block" onclick="saveProfileChanges()">Save</button>
                <button class="btn btn--outline btn--sm btn--block" onclick="initProfileSection()">Cancel</button>
            </div>
        </div>
    `;
}

function saveProfileChanges() {
    USER_DATA.name = document.getElementById('edit-name').value;
    USER_DATA.bio = document.getElementById('edit-bio').value;
    USER_DATA.location = document.getElementById('edit-location').value;
    USER_DATA.link = document.getElementById('edit-link').value;
    
    saveUserData();
    initProfileSection();
    
    // Also update navbar if needed (optional, app.js handles auth UI usually)
    if (window.updateAuthUI) window.updateAuthUI();
}

window.initProfileSection = initProfileSection;
window.handleGitHubConnect = handleGitHubConnect;
window.showEditProfile = showEditProfile;
window.saveProfileChanges = saveProfileChanges;
