// ===== USER PROFILE MODULE =====

// Load user data from localStorage or use defaults
const DEFAULT_USER_DATA = {
    name: 'SQL Learner',
    handle: 'sql_master_2024',
    bio: 'Mastering the art of data querying. Data Enthusiast | Future Data Scientist.',
    location: 'Global',
    link: 'https://github.com/sql-mastery',
    joined: 'Joined March 2024',
};

let USER_DATA = JSON.parse(localStorage.getItem('sql_user_profile')) || DEFAULT_USER_DATA;

function saveUserData() {
    localStorage.setItem('sql_user_profile', JSON.stringify(USER_DATA));
}

let PINNED_PROJECTS = JSON.parse(localStorage.getItem('sql_pinned_projects')) || [
    {
        name: 'ecommerce-analytics',
        desc: 'Complex analysis of sales data, customer behavior, and inventory management using recursive CTEs.',
        lang: 'SQL',
        stars: 8
    },
    {
        name: 'social-graph-query',
        desc: 'Identifying influence patterns and community clusters in a large-scale social network dataset.',
        lang: 'SQL',
        stars: 5
    }
];

function savePinnedProjects() {
    localStorage.setItem('sql_pinned_projects', JSON.stringify(PINNED_PROJECTS));
}

function initProfileSection() {
    const container = document.getElementById('section-profile');
    if (!container) return;

    container.innerHTML = `
        <div class="profile-container">
            <!-- Sidebar -->
            <aside class="profile-sidebar">
                <div class="profile-avatar">
                   <i data-lucide="user"></i>
                </div>
                <div class="user-info">
                    <h1 class="user-name">${USER_DATA.name}</h1>
                    <p class="user-handle">${USER_DATA.handle}</p>
                </div>
                <p class="user-bio">${USER_DATA.bio}</p>
                <div id="profile-actions">
                    <button class="btn btn--outline btn--block btn--sm" style="margin: 8px 0;" onclick="showEditProfile()">Edit profile</button>
                </div>
                
                <div class="user-meta" id="profile-meta-display">
                    <div class="user-meta-item">
                        <i data-lucide="map-pin" style="width: 16px;"></i>
                        <span>${USER_DATA.location}</span>
                    </div>
                    <div class="user-meta-item">
                        <i data-lucide="link" style="width: 16px;"></i>
                        <a href="${USER_DATA.link}" target="_blank" style="color: var(--text);">${USER_DATA.link.replace('https://', '') || 'No website'}</a>
                    </div>
                    <div class="user-meta-item">
                        <i data-lucide="calendar" style="width: 16px;"></i>
                        <span>${USER_DATA.joined}</span>
                    </div>
                </div>
            </aside>

            <!-- Main Content -->
            <main class="profile-main">
                <!-- Streak Graph -->
                <div class="streak-card">
                    <div class="streak-title">Loading contributions...</div>
                    <div class="streak-graph" id="contribution-graph">
                        <!-- Days generated by JS -->
                    </div>
                </div>

                <!-- Pinned Projects hidden per user request -->
                <!-- <div class="pinned-section">...</div> -->
            </main>
        </div>
    `;

    generateContributionGraph();
    
    if (window.lucide) {
        lucide.createIcons();
    }
}

function renderPinnedCard(project) {
    return ``; // Not used anymore
}

function generateContributionGraph() {
    const graph = document.getElementById('contribution-graph');
    if (!graph) return;

    let totalContributions = 0;
    const today = new Date();
    const oneYearAgo = new Date();
    oneYearAgo.setDate(today.getDate() - 370);

    let html = '';
    
    // Generate 371 days (GitHub style grid)
    for (let i = 0; i < 371; i++) {
        const date = new Date(oneYearAgo);
        date.setDate(oneYearAgo.getDate() + i);
        const dateString = date.toISOString().split('T')[0];
        
        const count = window.getActivityForDate ? window.getActivityForDate(dateString) : 0;
        totalContributions += count;
        
        let level = '';
        if (count >= 10) level = 'level-4';
        else if (count >= 5) level = 'level-3';
        else if (count >= 3) level = 'level-2';
        else if (count >= 1) level = 'level-1';
        
        const formattedDate = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        html += `<div class="streak-day ${level}" title="${count} contributions on ${formattedDate}"></div>`;
    }

    graph.innerHTML = html;
    
    const titleObj = document.querySelector('.streak-title');
    if (titleObj) {
        titleObj.textContent = `${totalContributions} contributions in the last year`;
    }
}

// GitHub Connection
function handleGitHubConnect() {
    const btn = document.getElementById('btn-github-connect');
    if (!btn) return;

    btn.innerHTML = `<i data-lucide="loader" class="spin" style="width: 14px;"></i> Connecting...`;
    lucide.createIcons();

    setTimeout(() => {
        btn.innerHTML = `<i data-lucide="github" style="width: 16px;"></i> Connected`;
        btn.classList.add('btn--success');
        lucide.createIcons();
        
        // Update user data with "Real" GitHub info
        USER_DATA.name = 'Kaustav Majumder'; // Sample name
        USER_DATA.handle = 'kaustav-m';
        USER_DATA.joined = 'Joined 2021';
        
        // If we are on profile section, re-render
        if (document.getElementById('section-profile').style.display !== 'none') {
            initProfileSection();
        }
        
        // Show success alert
        alert('Successfully linked with your GitHub account!');
    }, 1200);
}

function showEditProfile() {
    const container = document.querySelector('.profile-container');
    const user = JSON.parse(localStorage.getItem('sql_mastery_user')) || {};
    
    // Default values if missing
    const name = USER_DATA.name || '';
    const bio = USER_DATA.bio || '';
    const location = USER_DATA.location || '';
    const link = USER_DATA.link || '';
    const company = USER_DATA.company || '';
    const email = USER_DATA.email || user.email || '';
    const pronouns = USER_DATA.pronouns || "Don't specify";
    const avatarUrl = USER_DATA.avatarUrl || user.avatarUrl || `https://github.com/${(user.username || 'github').replace(/\s+/g, '')}.png`;

    container.innerHTML = `
        <div class="settings-layout" style="width: 100%; max-width: 900px; margin: 0 auto;">
            <div class="settings-main">
                <h2>Public profile</h2>
                
                <div class="form-group">
                    <label>Name</label>
                    <input type="text" id="edit-name" value="${name}" class="form-control">
                </div>
                
                <div class="form-group">
                    <label>Public email</label>
                    <select id="edit-email" class="form-control">
                        <option value="">Select a verified email to display</option>
                        <option value="${email}" ${email ? 'selected' : ''}>${email || 'user@example.com'}</option>
                    </select>
                    <p class="form-note">You can manage verified email addresses in your email settings.</p>
                </div>
                
                <div class="form-group">
                    <label>Bio</label>
                    <textarea id="edit-bio" class="form-control" style="height: 100px;">${bio}</textarea>
                    <p class="form-note">You can @mention other users and organizations to link to them.</p>
                </div>
                
                <div class="form-group">
                    <label>Pronouns</label>
                    <select id="edit-pronouns" class="form-control">
                        <option ${pronouns === "Don't specify" ? 'selected' : ''}>Don't specify</option>
                        <option ${pronouns === "he/him" ? 'selected' : ''}>he/him</option>
                        <option ${pronouns === "she/her" ? 'selected' : ''}>she/her</option>
                        <option ${pronouns === "they/them" ? 'selected' : ''}>they/them</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label><i data-lucide="link" style="width:16px; height:16px; margin-right:6px;"></i> URL</label>
                    <input type="text" id="edit-link" value="${link}" class="form-control">
                </div>
                
                <div class="form-group">
                    <label><i data-lucide="building" style="width:16px; height:16px; margin-right:6px;"></i> Company</label>
                    <input type="text" id="edit-company" value="${company}" class="form-control">
                </div>
                
                <div class="form-group">
                    <label><i data-lucide="map-pin" style="width:16px; height:16px; margin-right:6px;"></i> Location</label>
                    <input type="text" id="edit-location" value="${location}" class="form-control">
                </div>
                
                <h3 style="margin-top: 32px; font-weight: 500; border-bottom: 1px solid var(--border); padding-bottom: 8px; margin-bottom: 16px;">GitHub Integration</h3>
                <div class="form-group" style="background: var(--bg-hover); padding: 16px; border-radius: var(--radius); border: 1px solid var(--border);">
                    <p style="margin-bottom: 12px; font-size: 0.9rem;">Connect your GitHub account to directly create and push repositories from SQL Mastery.</p>
                    <button class="btn btn--outline" id="btn-github-auth" onclick="handleGitHubConnect()">
                        <i data-lucide="github" style="width:16px; height:16px; margin-right:4px;"></i> Connect GitHub Account
                    </button>
                    ${USER_DATA.githubConnected ? '<p style="color: var(--success); margin-top: 8px; font-size: 0.85rem;"><i data-lucide="check-circle" style="width:14px; height:14px; vertical-align:middle;"></i> Connected</p>' : ''}
                </div>

                <div style="margin-top: 32px; display: flex; gap: 8px;">
                    <button class="btn btn--success" onclick="saveProfileChanges()">Update profile</button>
                    <button class="btn btn--outline" onclick="initProfileSection()">Cancel</button>
                </div>
            </div>
            
            <div class="settings-sidebar">
                <label style="font-weight: 600; font-size: 0.9rem; display: block;">Profile picture</label>
                <img src="${avatarUrl}" onerror="this.src='https://github.com/github.png'" class="avatar-large" id="settings-avatar-preview">
                
                <div style="margin-top: 8px;">
                    <button class="btn btn--outline btn--sm" onclick="document.getElementById('avatar-upload-input').style.display = 'block'">Edit</button>
                    <div id="avatar-upload-input" style="display: none; margin-top: 8px;">
                        <input type="text" id="edit-avatar-url" class="form-control" placeholder="Paste image URL here" style="width: 100%; font-size: 0.8rem; margin-bottom: 8px;">
                        <button class="btn btn--outline btn--sm" onclick="const url = document.getElementById('edit-avatar-url').value; if(url) document.getElementById('settings-avatar-preview').src = url;">Preview</button>
                    </div>
                </div>
            </div>
        </div>
    `;
    
    if (window.lucide) lucide.createIcons();
}

function saveProfileChanges() {
    USER_DATA.name = document.getElementById('edit-name').value;
    USER_DATA.bio = document.getElementById('edit-bio').value;
    USER_DATA.location = document.getElementById('edit-location').value;
    USER_DATA.link = document.getElementById('edit-link').value;
    USER_DATA.company = document.getElementById('edit-company').value;
    USER_DATA.email = document.getElementById('edit-email').value;
    USER_DATA.pronouns = document.getElementById('edit-pronouns').value;
    
    const newAvatar = document.getElementById('edit-avatar-url') ? document.getElementById('edit-avatar-url').value : null;
    if (newAvatar) {
        USER_DATA.avatarUrl = newAvatar;
        const user = JSON.parse(localStorage.getItem('sql_mastery_user'));
        if (user) {
            user.avatarUrl = newAvatar;
            localStorage.setItem('sql_mastery_user', JSON.stringify(user));
        }
    }
    
    saveUserData();
    initProfileSection();
    
    // Also update navbar
    if (window.updateAuthUI) window.updateAuthUI();
}

window.initProfileSection = initProfileSection;
window.handleGitHubConnect = handleGitHubConnect;
window.showEditProfile = showEditProfile;
window.saveProfileChanges = saveProfileChanges;
