// ===== USER PROFILE MODULE =====

// Load user data from localStorage or use defaults
const DEFAULT_USER_DATA = {
    name: 'SQL Learner',
    handle: 'sql_master_2024',
    bio: 'Mastering the art of data querying. Data Enthusiast | Future Data Scientist.',
    location: 'Global',
    link: 'https://github.com/sql-mastery',
    joined: 'Joined March 2024',
};

let USER_DATA = JSON.parse(localStorage.getItem('sql_user_profile')) || DEFAULT_USER_DATA;

function saveUserData() {
    localStorage.setItem('sql_user_profile', JSON.stringify(USER_DATA));
}

let PINNED_PROJECTS = JSON.parse(localStorage.getItem('sql_pinned_projects')) || [
    {
        name: 'ecommerce-analytics',
        desc: 'Complex analysis of sales data, customer behavior, and inventory management using recursive CTEs.',
        lang: 'SQL',
        stars: 8
    },
    {
        name: 'social-graph-query',
        desc: 'Identifying influence patterns and community clusters in a large-scale social network dataset.',
        lang: 'SQL',
        stars: 5
    }
];

function savePinnedProjects() {
    localStorage.setItem('sql_pinned_projects', JSON.stringify(PINNED_PROJECTS));
}

function initProfileSection() {
    const container = document.getElementById('section-profile');
    if (!container) return;

    const avatarUrl = USER_DATA.avatarUrl || 'https://github.com/github.png';

    container.innerHTML = `
        <div class="profile-revamp">
            <div class="profile-header-new">
                <div class="profile-cover"></div>
                <div class="profile-info-grid">
                    <div class="profile-avatar-wrapper">
                        <img src="${avatarUrl}" class="avatar-img" id="main-avatar-img">
                        <div class="avatar-edit-badge" onclick="showEditProfile()">
                            <i data-lucide="camera"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class="profile-content-new">
                <div class="profile-sidebar-new">
                    <div class="user-primary-info">
                        <h1 class="user-name">${USER_DATA.name}</h1>
                        <p class="user-handle">@${USER_DATA.handle}</p>
                        <p class="user-bio">${USER_DATA.bio}</p>
                    </div>

                    <div class="user-metadata-new">
                        <div class="meta-item">
                            <i data-lucide="map-pin"></i>
                            <span>${USER_DATA.location}</span>
                        </div>
                        <div class="meta-item">
                            <i data-lucide="link"></i>
                            <a href="${USER_DATA.link}" target="_blank">${USER_DATA.link.replace('https://', '') || 'website.com'}</a>
                        </div>
                        <div class="meta-item">
                            <i data-lucide="calendar"></i>
                            <span>${USER_DATA.joined}</span>
                        </div>
                    </div>

                    <button class="btn btn--outline btn--block" onclick="showEditProfile()" style="margin-top: 24px;">
                        Edit Profile
                    </button>
                    
                    <div class="social-links-minimal">
                        <i data-lucide="github"></i>
                        <i data-lucide="twitter"></i>
                        <i data-lucide="linkedin"></i>
                    </div>
                </div>

                <div class="profile-main-new">
                    <div class="stats-overview-grid">
                        <div class="stat-card">
                            <span class="stat-value">Beginner</span>
                            <span class="stat-label">Level</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-value">12</span>
                            <span class="stat-label">Challenges</span>
                        </div>
                        <div class="stat-card">
                            <span class="stat-value">4</span>
                            <span class="stat-label">Dialects</span>
                        </div>
                    </div>

                    <div class="streak-card-new">
                        <div class="card-header-flex">
                            <h3 class="streak-title">Contribution Activity</h3>
                            <span class="total-year-count" id="total-contributions-count">0 in last year</span>
                        </div>
                        <div class="streak-graph-scroll">
                            <div class="streak-graph" id="contribution-graph">
                                <!-- Days generated by JS -->
                            </div>
                        </div>
                        <div class="graph-legend">
                            <span>Less</span>
                            <div class="legend-cells">
                                <div class="streak-day"></div>
                                <div class="streak-day level-1"></div>
                                <div class="streak-day level-2"></div>
                                <div class="streak-day level-3"></div>
                                <div class="streak-day level-4"></div>
                            </div>
                            <span>More</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    `;

    generateContributionGraph();
    
    if (window.lucide) {
        lucide.createIcons();
    }
}

function generateContributionGraph() {
    const graph = document.getElementById('contribution-graph');
    if (!graph) return;

    let totalContributions = 0;
    const today = new Date();
    const oneYearAgo = new Date();
    oneYearAgo.setDate(today.getDate() - 370);

    let html = '';
    
    for (let i = 0; i < 371; i++) {
        const date = new Date(oneYearAgo);
        date.setDate(oneYearAgo.getDate() + i);
        const dateString = date.toISOString().split('T')[0];
        
        const count = window.getActivityForDate ? window.getActivityForDate(dateString) : 0;
        totalContributions += count;
        
        let level = '';
        if (count >= 10) level = 'level-4';
        else if (count >= 5) level = 'level-3';
        else if (count >= 3) level = 'level-2';
        else if (count >= 1) level = 'level-1';
        
        const formattedDate = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        html += `<div class="streak-day ${level}" title="${count} contributions on ${formattedDate}"></div>`;
    }

    graph.innerHTML = html;
    
    const countDisplay = document.getElementById('total-contributions-count');
    if (countDisplay) {
        countDisplay.textContent = `${totalContributions} contributions in the last year`;
    }
}

function showEditProfile() {
    const container = document.querySelector('#section-profile');
    if (!container) return;

    const name = USER_DATA.name || '';
    const bio = USER_DATA.bio || '';
    const handle = USER_DATA.handle || '';
    const location = USER_DATA.location || '';
    const link = USER_DATA.link || '';
    const avatarUrl = USER_DATA.avatarUrl || 'https://github.com/github.png';

    container.innerHTML = `
        <div class="edit-profile-wrapper">
            <div class="edit-header">
                <h2>Edit Profile</h2>
                <button class="btn btn--ghost" onclick="initProfileSection()"><i data-lucide="x"></i></button>
            </div>
            
            <div class="edit-grid">
                <div class="edit-left">
                    <div class="avatar-upload-section">
                        <img src="${avatarUrl}" class="edit-avatar-preview" id="edit-avatar-preview">
                        <div class="upload-controls">
                            <label for="avatar-input" class="btn btn--sm btn--outline">
                                <i data-lucide="upload" style="width:14px; margin-right:4px;"></i> Upload new picture
                            </label>
                            <input type="file" id="avatar-input" accept="image/*" style="display:none;" onchange="previewProfileImage(this)">
                            <p class="text-muted" style="font-size:11px; margin-top:8px;">Max size 2MB. JPG or PNG.</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Display Name</label>
                        <input type="text" id="edit-name" value="${name}" class="form-control" placeholder="Your name">
                    </div>
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" id="edit-handle" value="${handle}" class="form-control" placeholder="handle">
                    </div>
                </div>

                <div class="edit-right">
                    <div class="form-group">
                        <label>Bio</label>
                        <textarea id="edit-bio" class="form-control" style="height: 100px;" placeholder="Tell us about yourself...">${bio}</textarea>
                    </div>
                    <div class="form-group">
                        <label>Location</label>
                        <input type="text" id="edit-location" value="${location}" class="form-control" placeholder="City, Country">
                    </div>
                    <div class="form-group">
                        <label>Website / Link</label>
                        <input type="text" id="edit-link" value="${link}" class="form-control" placeholder="https://yourlink.com">
                    </div>
                </div>
            </div>

            <div class="edit-footer">
                <button class="btn btn--outline" onclick="initProfileSection()">Cancel</button>
                <button class="btn btn--success" onclick="saveProfileChanges()">Save Changes</button>
            </div>
        </div>
    `;
    
    if (window.lucide) lucide.createIcons();
}

window.previewProfileImage = function(input) {
    if (input.files && input.files[0]) {
        const reader = new FileReader();
        reader.onload = function(e) {
            document.getElementById('edit-avatar-preview').src = e.target.result;
            USER_DATA.tempAvatar = e.target.result; // Store temporarily
        }
        reader.readAsDataURL(input.files[0]);
    }
}

function saveProfileChanges() {
    USER_DATA.name = document.getElementById('edit-name').value;
    USER_DATA.handle = document.getElementById('edit-handle').value;
    USER_DATA.bio = document.getElementById('edit-bio').value;
    USER_DATA.location = document.getElementById('edit-location').value;
    USER_DATA.link = document.getElementById('edit-link').value;
    
    if (USER_DATA.tempAvatar) {
        USER_DATA.avatarUrl = USER_DATA.tempAvatar;
        delete USER_DATA.tempAvatar;
    }
    
    saveUserData();
    initProfileSection();
    
    if (window.updateAuthUI) window.updateAuthUI();
}

window.initProfileSection = initProfileSection;
window.handleGitHubConnect = handleGitHubConnect;
window.showEditProfile = showEditProfile;
window.saveProfileChanges = saveProfileChanges;
